import { IRuleDecision } from "@isettingkit/input";
import { IEntry } from "@ptypes/design/table/IEntry";
import { IDetailsTabsConfig } from "../IDetailsTabsConfig";
import { IDecisionsDetails } from "../forms/IDecisionsDetails";

interface IMoreDetailsModalUI {
  data: IEntry;
  filteredTabsConfig: IDetailsTabsConfig;
  isSelected: string;
  portalId: string;
  smallScreenTab: boolean;
  decisions: IDecisionsDetails;
  isMobile: boolean;
  showGeneralDecisionsTab: boolean;
  showDecisionsRecip: boolean;
  showContribInserted: boolean;
  showContribDeleted: boolean;
  showDecisionsIncome: boolean;
  showIncomeInserted: boolean;
  showIncomeDeleted: boolean;
  showScoreModels: boolean;
  showScoreModelsInserted: boolean;
  showScoreModelsDeleted: boolean;
  showMinimum: boolean;
  showMinimumInserted: boolean;
  showMinimumDeleted: boolean;
  showBasicNotifFormat: boolean;
  showBasicNotifFormatInserted: boolean;
  showBasicNotifFormatDeleted: boolean;
  showBasicNotifRecipient: boolean;
  showBasicNotifRecipientInserted: boolean;
  showBasicNotifRecipientDeleted: boolean;
  showMinCredBureauRiskScore: boolean;
  showMinCredBureauRiskInserted: boolean;
  showMinCredBureauRiskDeleted: boolean;
  showNotifChannel: boolean;
  showNotifChanneInserted: boolean;
  showNotifChanneDeleted: boolean;
  showRiskScoreApiUrl: boolean;
  showRiskScoreApiUrlInserted: boolean;
  showRiskScoreApiUrlDeleted: boolean;
  showContribUpdated: boolean;
  showIncomeUpdated: boolean;
  showScoreModelsUpdated: boolean;
  showMinimumUpdated: boolean;
  showBasicNotifFormatUpdated: boolean;
  showBasicNotifRecipientUpdated: boolean;
  showMinCredBureauRiskUpdated: boolean;
  showNotifChanneUpdated: boolean;
  showRiskScoreApiUrlUpdated: boolean;
  loading: boolean;
  onCloseModal: () => void;
  onTabChange: (id: string) => void;
  contribQuotaInserted?: IRuleDecision[];
  contribQuotaDeleted?: IRuleDecision[];
  incomeQuotaInserted?: IRuleDecision[];
  incomeQuotaDeleted?: IRuleDecision[];
  scoreModelsInserted?: IRuleDecision[];
  scoreModelsDeleted?: IRuleDecision[];
  minimumInserted?: IRuleDecision[];
  minimumDeleted?: IRuleDecision[];
  basicNotifFormatInserted?: IRuleDecision[];
  basicNotifFormatDeleted?: IRuleDecision[];
  basicNotifRecipientInserted?: IRuleDecision[];
  basicNotifRecipientDeleted?: IRuleDecision[];
  minCredBureauRiskScoreInserted?: IRuleDecision[];
  minCredBureauRiskScoreDeleted?: IRuleDecision[];
  notifChannelInserted?: IRuleDecision[];
  notifChannelDeleted?: IRuleDecision[];
  riskScoreApiUrlInserted?: IRuleDecision[];
  riskScoreApiUrlDeleted?: IRuleDecision[];
  contribQuotaUpdated?: IRuleDecision[];
  incomeQuotaUpdated?: IRuleDecision[];
  scoreModelsUpdated?: IRuleDecision[];
  minimumUpdated?: IRuleDecision[];
  basicNotifFormatUpdated?: IRuleDecision[];
  basicNotifRecipientUpdated?: IRuleDecision[];
  minCredBureauRiskScoreUpdated?: IRuleDecision[];
  notifChannelUpdated?: IRuleDecision[];
  riskScoreApiUrlUpdated?: IRuleDecision[];
}

export type { IMoreDetailsModalUI };
