import { ITab } from "@inubekit/inubekit";
import { IRuleDecision } from "@isettingkit/input";
import { IDetailsTabsConfig } from "@ptypes/generalCredPolicies/IDetailsTabsConfig";
import { IEntry } from "@ptypes/design/table/IEntry";
import { IModalData } from "../IModalData";
import { IDecisionsDetails } from "../forms/IDecisionsDetails";

interface IDetailsRequest {
  data: IEntry;
  decisions: IDecisionsDetails;
  defaultSelectedTab: string;
  detailsTabsConfig: IDetailsTabsConfig;
  filteredTabsConfig: IDetailsTabsConfig;
  isMobile: boolean;
  isMoreDetails: boolean;
  isSelected: string;
  moreDetailsData: IEntry;
  showModal: boolean;
  showMoreDetailsModal: boolean;
  titleRequest: string;
  isSelectedRequest: string;
  filteredTabs: ITab[];
  showTrazabilityData: boolean;
  showErrorData: boolean;
  withErrorRequest: boolean;
  loading: boolean;
  modalData: IModalData;
  showDecision: boolean;
  labelButton: string;
  iconButton: React.ReactElement;
  onTabRequestChange: (id: string) => void;
  onThirdClick: () => void;
  onTabChange: (id: string) => void;
  onToggleModal: () => void;
  onToggleMoreDetailsModal: () => void;
  minimumInserted?: IRuleDecision[];
  minimumDeleted?: IRuleDecision[];
  contribQuotaInserted?: IRuleDecision[];
  contribQuotaDeleted?: IRuleDecision[];
  incomeQuotaInserted?: IRuleDecision[];
  incomeQuotaDeleted?: IRuleDecision[];
  scoreModelsInserted?: IRuleDecision[];
  scoreModelsDeleted?: IRuleDecision[];
  basicNotifFormatInserted?: IRuleDecision[];
  basicNotifFormatDeleted?: IRuleDecision[];
  basicNotifRecipientInserted?: IRuleDecision[];
  basicNotifRecipientDeleted?: IRuleDecision[];
  minCredBureauRiskScoreInserted?: IRuleDecision[];
  minCredBureauRiskScoreDeleted?: IRuleDecision[];
  notifChannelInserted?: IRuleDecision[];
  notifChannelDeleted?: IRuleDecision[];
  riskScoreApiUrlInserted?: IRuleDecision[];
  riskScoreApiUrlDeleted?: IRuleDecision[];
}

export type { IDetailsRequest };
