import { FormikProps } from "formik";
import { ITab } from "@inubekit/inubekit";
import { ISaveDataResponse } from "@ptypes/saveData/ISaveDataResponse";
import { IRequestSteps } from "@ptypes/design/IRequestSteps";
import { IRuleDecisionExtended } from "@ptypes/IRuleDecisionExtended";
import { IDecisionsGeneralEntry } from "../forms/IDecisionsGeneralEntry";
import { IModalData } from "../IModalData";

interface IEditGeneralPoliciesUI {
  filteredTabsConfig: ITab[];
  contributionsPortfolio: IRuleDecisionExtended[];
  isSelected: string;
  requestSteps: IRequestSteps[];
  loading: boolean;
  showPendingReqModal: boolean;
  showDateModal: boolean;
  showRequestProcessModal: boolean;
  saveGeneralPolicies: ISaveDataResponse;
  smallScreen: boolean;
  formValues: IDecisionsGeneralEntry;
  initialDecisionsData: IDecisionsGeneralEntry;
  decisionsGeneralReference: React.RefObject<FormikProps<IDecisionsGeneralEntry> | null>;
  incomePortfolio: IRuleDecisionExtended[];
  scoreModels: IRuleDecisionExtended[];
  minimumIncomePercentage: IRuleDecisionExtended[];
  showDecisionsGeneral: boolean;
  showIncomePort: boolean;
  showContributions: boolean;
  showScoreModels: boolean;
  showMinimumIncome: boolean;
  showGoBackModal: boolean;
  isRequestStatusModal: boolean;
  heightContPageContribut: string;
  heightContPageIncome: string;
  heightContPageScoreModels: string;
  heightContPageMinimum: string;
  modalData: IModalData;
  showDecision: boolean;
  onEditedModal: () => void;
  setShowReciprocity: React.Dispatch<React.SetStateAction<boolean>>;
  setShowFactor: React.Dispatch<React.SetStateAction<boolean>>;
  onToggleDateModal: () => void;
  setIncomePortfolio: (decisions: IRuleDecisionExtended[]) => void;
  setScoreModels: (decisions: IRuleDecisionExtended[]) => void;
  setMinimumIncomePercentage: (decisions: IRuleDecisionExtended[]) => void;
  onTabChange: (id: string) => void;
  onReset: () => void;
  setContributionsPortfolio: (decisions: IRuleDecisionExtended[]) => void;
  setIsCurrentFormValid: React.Dispatch<React.SetStateAction<boolean>>;
  onCloseRequestStatus: () => void;
  onClosePendingReqModal: () => void;
  onCloseProcess: () => void;
  normalizeEvaluateRuleData?: IRuleDecisionExtended[];
  normalizedContributions?: IRuleDecisionExtended[];
  normalizedIncome?: IRuleDecisionExtended[];
  normalizedScoreModels?: IRuleDecisionExtended[];
  normalizedMinimumIncome?: IRuleDecisionExtended[];
}

export type { IEditGeneralPoliciesUI };
