const monthNames = [
  { id: 1, code: 1, month: "January" },
  { id: 2, code: 2, month: "February" },
  { id: 3, code: 3, month: "March" },
  { id: 4, code: 4, month: "April" },
  { id: 5, code: 5, month: "May" },
  { id: 6, code: 6, month: "June" },
  { id: 7, code: 7, month: "July" },
  { id: 8, code: 8, month: "August" },
  { id: 9, code: 9, month: "September" },
  { id: 10, code: 10, month: "October" },
  { id: 11, code: 11, month: "November" },
  { id: 12, code: 12, month: "December" },
  { id: 13, code: 1, month: "Enero" },
  { id: 14, code: 2, month: "Febrero" },
  { id: 15, code: 3, month: "Marzo" },
  { id: 16, code: 4, month: "Abril" },
  { id: 17, code: 5, month: "Mayo" },
  { id: 18, code: 6, month: "Junio" },
  { id: 19, code: 7, month: "Julio" },
  { id: 20, code: 8, month: "Agosto" },
  { id: 21, code: 9, month: "Septiembre" },
  { id: 22, code: 10, month: "Octubre" },
  { id: 23, code: 11, month: "Noviembre" },
  { id: 24, code: 12, month: "Deciembre" },
];

export { monthNames };
