const addCycleLabels = {
  nameCycle: "Nombre del ciclo",
  periodicity: "Periodicidad de ciclo",
  paydayTranslation: "Día de pago",
  payday: "Día de pago",
  typePayment: "Tipo de pago",
  numberDaysUntilCut: "# de días para el corte",
  laborRegulatorFramework: "Marco normativo laboral",
  palceholderLaborRegulator: "Selecciona de la lista",
  placeholderNameCycle: "Nombre",
  placeholderPeriodicity: "Selecciona de la lista",
  placeholderPayday: "Selecciona de la lista",
  placeholderTypePayment: "Selecciona de la lista",
  placeholderNumberDaysUntilCut: "Selecciona de la lista",
  placeholderMonth: "Mes",
  placeholderDay: "Día",
  maxLengthNameCycle: 20,
  cycleDescription: "Ciclo de pago",
};
export { addCycleLabels };
