const infoRulesMessage = (ruleLabel: string) => {
  return {
    LoanTerm: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    RepaymentStructure: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    GeometricGradientRepaymentRate: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ArithmeticGradientRepaymentValue: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ModeOfDisbursementType: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    SuggestedPaymentChannelType: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    PercentagePayableViaExtraInstallments: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    PaymentChannelTypeForExtraInstallments: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    AdjustmentInterestPaymentType: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    LineOfCredit: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ChannelsCreditByLine: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    LoanAmountLimit: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    MaximumPremiumPercentageForExtraordinaryInstallmentsCommitments: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    PercentageOfMonthlyCapacityForLimit: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    IsExcludedFromLimitAnalysisByPaymentCapacity: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    InterestRateType: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    InterestRateFixedPoints: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ReferenceRateForFixedPoints: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    CreditRiskPremium: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    FixedInterestRate: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ChargeMonthlyRateForAdditionalLoanCosts: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ApprovalBoardPositions: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    IndicatorForAutomaticManualApproval: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    PositionsAuthorizedToApproveOnBehalfOfApprover: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    HasAtomaticCollection: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ExclusiveCreditLines: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    PositionsAuthorizedForExtemporaneousSystemValidationRequirementsApproval: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    OmittableHumanTasks: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    AutomaticCollectionForExclusiveCreditLines: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    EstimatedDaysForLoanDisbursementProcess: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    ConsolidationOfOtherCreditProductsAllowed: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    FinancialObligationsUpdateRequired: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    GuaranteeRequirements: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    AdditionalBorrowersAllowed: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    BondCalculationFactorByAmount: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    Requirement: `En este paso encontraras la información de la decisión ${ruleLabel}`,
    Default: `En este paso encontraras la información de esta decisión. `,
  };
};

export { infoRulesMessage };
